server:
  port: 9200
spring:
  application:
    name: user-auth
  redis:
    host: 192.168.26.100
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.26.100:3306/foxes-novel?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true  # 允许覆盖注册
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:9761/eureka
auth:
  ttl: 3600  #token存储到redis的过期时间
  clientId: changgou #客户端id
  clientSecret: changgou #客户端秘钥
  cookieDomain: localhost #Cookie保存对应的域名
  cookieMaxAge: -1 #cookie过期时间 , -1标识浏览器关闭随即销毁
encrypt:
  key-store:
    location: classpath:/changgou.jks
    secret: changgou
    alias: changgou
    password: changgou
#logging:
#  level:
#    root: DEBUG
---
#gzx
spring:
  profiles: gzx-test
  redis:
    host: 192.168.170.138
    port: 6379
    password: