server:
  port: 80


eureka:
  client:
    service-url:
      defaultZone: http://localhost:9761/eureka
      register-with-eureka: true #注册
      fetch-registry: true #拉取


spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*" #允许所有请求跨域
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        # 章节微服务
        - id: chapter # 唯一标识
          uri: lb://chapter-service # 转发路径(good 服务)
          predicates:
            - Path=/chapter/** # 条件，用于请求网关路径的匹配规则
          filters:
            - StripPrefix= 1
        # 小说微服务
        - id: book # 唯一标识
          uri: lb://book-service # 转发路径(good 服务)
          predicates:
            - Path=/book/** # 条件，用于请求网关路径的匹配规则
          filters:
            - StripPrefix= 1
        # 搜索微服务
        - id: search # 唯一标识
          uri: lb://SEARCH-SERVICE # 转发路径(search 服务)
          predicates:
            - Path=/search/** # 条件，用于请求网关路径的匹配规则
          filters:
            - StripPrefix= 1
        - id: homepage # 唯一标识
          uri: lb://homepage-service # 转发路径(homepage 服务)
          predicates:
            - Path=/** # 条件，用于请求网关路径的匹配规则
          filters:
            - StripPrefix= 0

management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true
logging:
  level:
    root: debug