server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9761/eureka
    fetch-registry: true   # 是否拉取注册信息
    register-with-eureka: true   # 是否注册到eureka


spring:
  application:
    name: book-service
  datasource:
    url: jdbc:mysql://192.168.26.100:3306/foxes-novel?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root